### PR TITLE
Impove dependencies management and helpers

### PR DESCRIPTION
**Pull request by Jibec**
Hi, I noticed a few things to improve in this package, especially, dependencies.
It does brings a lot of new packages, I wanted to make sure they can safely be removed without side effects

### CODE REVIEW

**Comment by sy6sy2** [comment]
Hi Jibec,
First of all thank you for your interest in this package and your PR.
I would like to improve an update it more frequently but my thesis takes a lot of my time.

I will take a look at your changes in order to merge as soon as I can.

Maybe if you want you can join this repo as contributor? But I think that I don't have the privilege to do it.

Thank you!

**Comment by Jibec** [comment]
There is no need for me to be a contributor of this repository, it can wait as long as needed :+1:

**Comment by Gredin67** [comment]
It looks like conf/kodi.list has disappeared. Any hint? @sy6sy2 @Jibec

**Comment by Gredin67** [comment]
guess this is resolved by #9

**Pull request closed without merging**
