### PR TITLE
Example

### PR DESCRIPTION
**Pull request by yalh76**
## Problem
- *Improve Kodi*

## Solution
- *Apply example_ynh*

## PR Status
- [ ] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Package_check results
---
* An automatic package_check will be launch at https://ci-apps-dev.yunohost.org/, when you add a specific comment to your Pull Request: "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!"*

### CODE REVIEW

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Comment by gautz** [comment]
@yalh76 did it work on x86 for you? I managed to install properly some months ago but I had sme harware

**Comment by yalh76** [comment]
As far as I have tested, Yes It worked. But can't be automatically tested because it requires a graphic card and the CI_package_check don't have one... That's why I stopped working on it.

**Comment by gautz** [comment]
oh yea I just saw our thread in the issues. I'll try to find someone to test on a appropriate hardware.

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Pull request merged**
